# Generated by Django 3.0.7 on 2020-08-16 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Phone name')),
                ('description', models.TextField(verbose_name='Description')),
                ('staticpath', models.CharField(max_length=256, verbose_name='Path to static file')),
                ('visible_status', models.CharField(choices=[('v', 'Visible'), ('i', 'Invisible')], default='v', max_length=1, verbose_name='Visible status')),
            ],
        ),
        migrations.CreateModel(
            name='CartCompanion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ManyToManyField(related_name='carts', to='shop.Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish date')),
                ('visible_status', models.CharField(choices=[('v', 'Visible'), ('i', 'Invisible')], default='v', max_length=1, verbose_name='Visible status')),
                ('phones', models.ManyToManyField(to='shop.Phone')),
            ],
        ),
    ]
