# Generated by Django 2.2.14 on 2020-08-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='visible_status',
            field=models.CharField(default='v', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Phone name'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='staticpath',
            field=models.CharField(max_length=256, verbose_name='Path to static file'),
        ),
    ]
