# Generated by Django 3.0.7 on 2020-08-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200816_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('p', 'Phone'), ('c', 'Consoles'), ('a', 'Accessories'), ('o', 'Other')], default='p', max_length=1, verbose_name='Type'),
        ),
    ]
