# Generated by Django 3.0.7 on 2020-08-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_sitefield_visible_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefield',
            name='dropdown_fields',
            field=models.ManyToManyField(blank=True, null=True, to='shop.SiteField'),
        ),
        migrations.AlterField(
            model_name='sitefield',
            name='handler',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
