# Generated by Django 3.0.7 on 2020-08-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200816_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitefield',
            name='main',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sitefield',
            name='dropdown_fields',
            field=models.ManyToManyField(to='shop.SiteField'),
        ),
    ]
