# Generated by Django 3.0.7 on 2020-08-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200816_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefield',
            name='handler',
            field=models.CharField(default='#', max_length=128),
        ),
    ]
