# Generated by Django 3.0.7 on 2020-08-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200816_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefield',
            name='dropdown_fields',
            field=models.ManyToManyField(blank=True, null=True, to='shop.SiteField'),
        ),
    ]
