# Generated by Django 3.0.7 on 2020-08-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200816_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.CartCompanion')),
                ('phones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Phone')),
            ],
        ),
        migrations.CreateModel(
            name='CartCompanionSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.CartCompanion')),
                ('phones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Phone')),
            ],
        ),
        migrations.RemoveField(
            model_name='cartcompanion',
            name='cart',
            field=models.ManyToManyField(related_name='carts', to='shop.Phone'),
        ),
        migrations.AddField(
            model_name='cartcompanion',
            name='cart',
            field=models.ManyToManyField(related_name='carts', through='shop.CartCompanionSupport', to='shop.Phone'),
        )
    ]