# Generated by Django 3.0.7 on 2020-08-16 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200816_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phones',
            field=models.ManyToManyField(to='shop.Phone'),
        ),
        migrations.AddField(
            model_name='order',
            name='phones',
            field=models.ManyToManyField(through='shop.OrderSupport', to='shop.Phone'),
        ),
        migrations.AlterField(
            model_name='ordersupport',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
    ]
