# Generated by Django 3.0.7 on 2020-08-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200816_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersupport',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
