# Generated by Django 3.0.7 on 2020-08-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_ordersupport_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersupport',
            name='count',
            field=models.CharField(default='1', max_length=8),
        ),
    ]
