# Generated by Django 3.0.7 on 2020-08-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200816_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartcompanionsupport',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordersupport',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
