# Generated by Django 3.1 on 2020-08-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200819_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('p', 'Phone'), ('c', 'Console'), ('a', 'Accessory'), ('m', 'Monitor'), ('o', 'Other')], default='p', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='view',
            name='phone_type',
            field=models.CharField(choices=[('p', 'Phone'), ('c', 'Console'), ('a', 'Accessory'), ('m', 'Monitor'), ('o', 'Other')], max_length=1),
        ),
    ]
