# Generated by Django 3.1 on 2020-08-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_route_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='visible_status',
            field=models.CharField(choices=[('v', 'Visible'), ('i', 'Invisible')], default='v', max_length=1, verbose_name='Visible status'),
        ),
        migrations.AddField(
            model_name='type',
            name='visible_status',
            field=models.CharField(choices=[('v', 'Visible'), ('i', 'Invisible')], default='v', max_length=1, verbose_name='Visible status'),
        ),
        migrations.AddField(
            model_name='view',
            name='visible_status',
            field=models.CharField(choices=[('v', 'Visible'), ('i', 'Invisible')], default='v', max_length=1, verbose_name='Visible status'),
        ),
    ]
