# Generated by Django 3.1 on 2020-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20200819_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.AddField(
            model_name='view',
            name='link',
            field=models.CharField(default='-', max_length=128),
            preserve_default=False,
        ),
    ]
