# Generated by Django 3.1 on 2020-08-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200819_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(default='p', max_length=32, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='view',
            name='phone_type',
            field=models.CharField(choices=[('p', 'Phone'), ('c', 'Console'), ('a', 'Accessory'), ('m', 'Monitor'), ('o', 'Other'), ('H', 'AndHuman')], max_length=1),
        ),
    ]
