# Generated by Django 3.1 on 2020-08-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20200821_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='phone_type',
            field=models.CharField(max_length=32),
        ),
    ]
