# Generated by Django 3.1 on 2020-08-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20200821_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='View',
        ),
        migrations.AddField(
            model_name='sitefield',
            name='phone_type',
            field=models.CharField(default='p', max_length=32),
            preserve_default=False,
        ),
    ]
