# Generated by Django 3.1 on 2020-08-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20200821_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitefield',
            name='exclude',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
