# Generated by Django 3.1 on 2020-08-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_sitefield_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefield',
            name='handler',
            field=models.CharField(blank=True, default='#', max_length=128, null=True),
        ),
    ]
