# Generated by Django 3.1 on 2020-08-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20200826_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefield',
            name='phone_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
