# Generated by Django 3.1 on 2020-08-29 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20200827_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sitefield', verbose_name='Type'),
        ),
    ]
